In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np

In [ ]:
data=load_breast_cancer()

In [ ]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [ ]:
df=pd.DataFrame(data=data.data,columns=data.feature_names)

In [ ]:
df['Target']=pd.DataFrame(data=data.target)

In [ ]:
df.sample(7)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
321,20.16,19.66,131.10,1274.0,0.08020,0.08564,0.11550,0.077260,0.1928,0.05096,...,23.03,150.20,1657.0,0.10540,0.15370,0.26060,0.14250,0.3055,0.05933,0
252,19.73,19.82,130.70,1206.0,0.10620,0.18490,0.24170,0.097400,0.1733,0.06697,...,25.59,159.80,1933.0,0.17100,0.59550,0.84890,0.25070,0.2749,0.12970,0
457,13.21,25.25,84.10,537.9,0.08791,0.05205,0.02772,0.020680,0.1619,0.05584,...,34.23,91.29,632.9,0.12890,0.10630,0.13900,0.06005,0.2444,0.06788,1
362,12.76,18.84,81.87,496.6,0.09676,0.07952,0.02688,0.017810,0.1759,0.06183,...,25.99,87.82,579.7,0.12980,0.18390,0.12550,0.08312,0.2744,0.07238,1
278,13.59,17.84,86.24,572.3,0.07948,0.04052,0.01997,0.012380,0.1573,0.05520,...,26.10,98.91,739.1,0.10500,0.07622,0.10600,0.05185,0.2335,0.06263,1
289,11.37,18.89,72.17,396.0,0.08713,0.05008,0.02399,0.021730,0.2013,0.05955,...,26.14,79.29,459.3,0.11180,0.09708,0.07529,0.06203,0.3267,0.06994,1
231,11.32,27.08,71.76,395.7,0.06883,0.03813,0.01633,0.003125,0.1869,0.05628,...,33.75,79.82,452.3,0.09203,0.14320,0.10890,0.02083,0.2849,0.07087,1


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('Target',axis=1),df['Target'],test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [ ]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [ ]:
#Numpy arrays to tensor

In [ ]:
import torch

In [ ]:
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)
y_train_tensor=torch.from_numpy(y_train.values)
y_test_tensor=torch.from_numpy(y_test.values)

In [ ]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

# Model

In [ ]:
class SimpleNN():
  def __init__(self,X):
    torch.manual_seed(42)
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z= torch.matmul(X,self.weights) + self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_cal(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    loss=-(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred))
    return loss.mean()



In [ ]:
learning_rate=0.1
epochs=25

# Pipeline

In [ ]:
model=SimpleNN(x_train_tensor)
model.weights

tensor([[0.0582],
        [0.0629],
        [0.1236],
        [0.0526],
        [0.5262],
        [0.4768],
        [0.9552],
        [0.9288],
        [0.0835],
        [0.1326],
        [0.1571],
        [0.3754],
        [0.8425],
        [0.8705],
        [0.3775],
        [0.6124],
        [0.0881],
        [0.7012],
        [0.6234],
        [0.4373],
        [0.0747],
        [0.6834],
        [0.3122],
        [0.3091],
        [0.0313],
        [0.0404],
        [0.9319],
        [0.1521],
        [0.2650],
        [0.1304]], dtype=torch.float64, requires_grad=True)

In [ ]:
#loop
for epoch in range(epochs):
  #Forward
  y_pred=model.forward(x_train_tensor)

  #Loss
  loss=model.loss_cal(y_pred,y_train_tensor)

  #Backprop
  loss.backward()

  #Update weights
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  #since gradients accumulate zero them
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"Epoch:{epoch},loss={loss.item()}")



Epoch:0,loss=3.017367178870535
Epoch:1,loss=2.8435418055273973
Epoch:2,loss=2.6711146534342163
Epoch:3,loss=2.4964802240206616
Epoch:4,loss=2.321519645827882
Epoch:5,loss=2.1512523674268516
Epoch:6,loss=1.985225047626649
Epoch:7,loss=1.8238489005115959
Epoch:8,loss=1.6698970749190682
Epoch:9,loss=1.5252966727980857
Epoch:10,loss=1.3934921897164914
Epoch:11,loss=1.272857608750351
Epoch:12,loss=1.1653516999401752
Epoch:13,loss=1.074759942903053
Epoch:14,loss=1.0006138355851286
Epoch:15,loss=0.941508782474363
Epoch:16,loss=0.8953039317811864
Epoch:17,loss=0.8595187976076935
Epoch:18,loss=0.8317536406571102
Epoch:19,loss=0.8099636763805694
Epoch:20,loss=0.7925525872528114
Epoch:21,loss=0.7783449899691972
Epoch:22,loss=0.7665071256215764
Epoch:23,loss=0.7564597167723855
Epoch:24,loss=0.7478027914614758


Model evaluation


In [ ]:
with torch.no_grad():
  y_pred=model.forward(x_test_tensor)
# original target is either 0 or 1,so we need to conver y_pred to 0 or 1 with threshold 0.5
  y_pred=(y_pred>0.5).float()

  #Accuracy
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy:{accuracy}")

Accuracy:0.5366266369819641


In [ ]:
_